# Generated by Django 5.1 on 2025-08-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0003_pledge"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledge",
            name="anonymous",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
