# Generated by Django 5.1 on 2025-08-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0005_remove_comment_commentator_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundraiser",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundraiser",
            name="genre_type",
            field=models.CharField(
                choices=[
                    ("drama", "Drama"),
                    ("poem", "Poem"),
                    ("selfhelp", "Self Help"),
                    ("romantic", "Romantic"),
                    ("crime", "Crime"),
                ],
                default="drama",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fundraiser",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
