# Generated by Django 5.1 on 2025-08-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0006_fundraiser_end_date_fundraiser_genre_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledge",
            name="tier_level",
            field=models.IntegerField(
                choices=[
                    (1, "Tier 1:Baisc"),
                    (2, "Tier 2:Hard Copy"),
                    (3, "Tier 3:Signed Copy"),
                ],
                default=1,
            ),
        ),
    ]
