# Generated by Django 5.1 on 2025-09-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0007_pledge_tier_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="genre_type",
            field=models.CharField(
                choices=[
                    ("drama", "Drama"),
                    ("poem", "Poem"),
                    ("selfhelp", "Self Help"),
                    ("romantic", "Romantic"),
                    ("crime", "Crime"),
                    ("thriller", "Thriller"),
                    ("fantasy", "Fantasy"),
                    ("scifi", "Sci-Fi"),
                    ("biography", "Biography"),
                    ("history", "History"),
                    ("children", "Children"),
                    ("youngadult", "Young Adult"),
                    ("nonfiction", "Non-Fiction"),
                    ("other", "Other"),
                ],
                default="drama",
                max_length=20,
            ),
        ),
    ]
