# Generated by Django 5.1 on 2025-09-06 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0008_alter_fundraiser_genre_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="genre_type",
            field=models.CharField(
                choices=[
                    ("drama", "Drama"),
                    ("romance", "Romance"),
                    ("crime", "Crime"),
                    ("thriller", "Thriller"),
                    ("fantasy", "Fantasy"),
                    ("scifi", "Sci-Fi"),
                    ("youngadult", "Young Adult"),
                    ("children", "Children"),
                    ("selfhelp", "Self-Help"),
                    ("biography", "Biography"),
                    ("history", "History"),
                    ("knowledge", "Knowledge"),
                    ("poem", "Poem"),
                    ("classic", "Classic"),
                    ("modern", "Modern"),
                    ("short", "Short"),
                    ("picture", "Picture"),
                    ("middle", "Middle"),
                    ("ya", "Young Adult"),
                    ("misc", "Misc"),
                ],
                default="drama",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fundraiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="fundraisers.fundraiser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "fundraiser")},
            },
        ),
    ]
