# Generated by Django 5.2.8 on 2025-11-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0009_alter_fundraiser_genre_type_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="genre_type",
            field=models.CharField(
                choices=[
                    ("drama", "Drama"),
                    ("romance", "Romance"),
                    ("crime", "Crime"),
                    ("thriller", "Thriller"),
                    ("fantasy", "Fantasy"),
                    ("scifi", "Sci-Fi"),
                    ("youngadult", "Young Adult"),
                    ("children", "Children"),
                    ("selfhelp", "Self-Help"),
                    ("biography", "Biography"),
                    ("history", "History"),
                    ("knowledge", "Knowledge"),
                    ("poem", "Poem"),
                    ("classic", "Classic"),
                    ("modern", "Modern"),
                    ("short", "Short"),
                    ("picture", "Picture"),
                    ("middle", "Middle"),
                    ("misc", "Misc"),
                ],
                default="drama",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fundraiser",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="fundraiser_images/"
            ),
        ),
    ]
